version: 3.9
services:
    web:
        build: .
        ports: 8000:8000
        command: gunicorn biblia.wsgi
        env_file:
            - ./.env.dev
        depends_on:
            - postgres
    postgres:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=hello_django
            - POSTGRES_PASSWORD=hello_django
            - POSTGRES_DB=hello_django_dev

volumes:
    postgres_data:
