FROM python:3.9-slim-buster

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV DJANGO_DEBUG True

COPY requirements requirements
RUN python -m pip install --upgrade pip && pip install -r requirements/requirements.txt

RUN addgroup --system app && adduser --system app --ingroup app

ENV HOME=/home/app
ENV APP_HOME=/home/app/web
WORKDIR $APP_HOME

USER app

#RUN python manage.py collectstatic
EXPOSE 8000
ENTRYPOINT ["/home/app/web/entrypoint.sh"]
CMD gunicorn wsgi:application --bind 0.0.0.0:8000
