services:
    db:
        image: postgres:13.3-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env
        ports:
          - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U bibliothekai"]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    postgres_data:
