FROM node:17-alpine3.14 AS node-build
COPY package.json /
RUN npm install
COPY . /app
WORKDIR /app
RUN npm run build:development


FROM python:3.9-slim-buster

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV DJANGO_DEBUG True

COPY requirements requirements
RUN python -m pip install --upgrade pip && pip install -r requirements/requirements.txt

ENV HOME=/home/app
ENV APP_HOME=/home/app/web
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME

COPY --from=node-build /app/dist ${APP_HOME}/translations/static

EXPOSE 8000
