# Generated by Django 3.0.8 on 2020-07-20 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0007_auto_20200719_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='personrole',
            name='role',
            field=models.CharField(choices=[('ED', 'Editor'), ('AU', 'Author'), ('IN', 'Introducer'), ('CM', 'Commentator')], max_length=2),
        ),
        migrations.AddField(
            model_name='volume',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='translations.Series'),
        ),
    ]
