# Generated by Django 3.0.8 on 2020-07-20 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0008_auto_20200719_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='translations.Series'),
        ),
    ]
