# Generated by Django 3.0.8 on 2020-09-30 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0010_auto_20200926_1253"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="language",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="translations.Language",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="feature",
            name="kind",
            field=models.TextField(
                blank=True, choices=[("PR", "Prose"), ("VR", "Verse")]
            ),
        ),
        migrations.AlterField(
            model_name="sourcetext",
            name="original_language_title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
