# Generated by Django 3.0.8 on 2020-10-05 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0013_auto_20201004_1604"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="feature",
            field=models.CharField(
                choices=[
                    ("ED", "Edited by"),
                    ("IN", "Introduction by"),
                    ("CM", "Commentary by"),
                    ("TR", "Translation by"),
                    ("NT", "Notes by"),
                ],
                max_length=2,
            ),
        ),
    ]
