# Generated by Django 3.0.8 on 2020-10-12 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0022_auto_20201011_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
