# Generated by Django 3.0.8 on 2020-11-20 04:53

import django.db.models.expressions
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0023_volume_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={
                "ordering": [
                    django.db.models.expressions.Case(
                        django.db.models.expressions.When(
                            sole_name="", then="last_name"
                        ),
                        django.db.models.expressions.When(
                            last_name="", then="sole_name"
                        ),
                    ),
                    "first_name",
                    "middle_name",
                ]
            },
        ),
    ]
