# Generated by Django 3.0.8 on 2020-11-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0025_auto_20201108_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='recommended',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
