# Generated by Django 3.0.8 on 2020-11-23 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0024_auto_20201119_2153'),
        ('translations', '0026_review_recommended'),
    ]

    operations = [
    ]
