# Generated by Django 3.0.8 on 2020-11-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0028_auto_20201125_2018"),
    ]

    operations = [
        migrations.AddField(
            model_name="publishedreview",
            name="published_date",
            field=models.DateTimeField(null=True),
        ),
    ]
