# Generated by Django 3.0.8 on 2020-11-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0029_publishedreview_published_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publishedreview",
            name="published_date",
            field=models.DateField(null=True),
        ),
    ]
