# Generated by Django 3.0.8 on 2020-12-13 01:41

from django.db import migrations


def populate_sort_name(apps, schema_editor):
    Person = apps.get_model("translations", "Person")
    for p in Person.objects.all():
        p.sort_name = (
            p.sole_name
            if p.sole_name
            else f"{p.last_name}, {p.first_name} {p.middle_name}".strip()
        )
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0035_auto_20201212_1833"),
    ]

    operations = [
        migrations.RunPython(populate_sort_name, migrations.RunPython.noop),
    ]
