# Generated by Django 3.1.4 on 2021-01-10 05:50

from django.db import migrations


def convert_original_language_titles(apps, schema_editor):
    SourceText = apps.get_model("translations", "SourceText")
    AlternateName = apps.get_model("translations", "AlternateName")
    ContentType = apps.get_model("contenttypes", "ContentType")
    ct = ContentType.objects.get_for_model(SourceText)

    for s in SourceText.objects.all():
        if s.original_language_title:
            alt = AlternateName(
                name=s.original_language_title,
                alternate_name_type="OR",
                object_id=s.id,
                content_type=ct,
            )
            alt.save()


class Migration(migrations.Migration):
    dependencies = [
        ("translations", "0039_alternatename_alternate_name_type"),
    ]
    operations = [
        migrations.RunPython(
            convert_original_language_titles, migrations.RunPython.noop
        ),
    ]
