# Generated by Django 3.1.4 on 2021-05-30 02:21

from django.db import migrations, models


def populate_original_publication_date(apps, schema_editor):
    Feature = apps.get_model("translations", "Feature")
    for f in Feature.objects.all():
        if f.feature == "TR" and f.volume.published_date:
            f.original_publication_date = f.volume.published_date
            f.save()


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0048_auto_20210516_1120"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="original_publication_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(
            populate_original_publication_date, migrations.RunPython.noop
        ),
    ]
