# Generated by Django 3.0.8 on 2020-07-19 05:12

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0004_auto_20200718_2147"),
    ]

    operations = [
        migrations.AddField(
            model_name="publisher",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="publisher",
            name="website",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="review",
            name="title",
            field=models.CharField(default="Test", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="volume",
            name="published_date",
            field=models.DateField(
                blank=True, default=datetime.datetime(2020, 7, 18, 23, 12, 13, 589431)
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="publishedreview",
            name="volume",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="translations.Volume",
            ),
        ),
    ]
