# Generated by Django 3.0.8 on 2020-07-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0006_auto_20200719_1740"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volume",
            name="isbn",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
