# Generated by Django 3.0.8 on 2020-09-26 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0009_auto_20200719_1801"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("ED", "Edited by"),
                            ("IN", "Introduction by"),
                            ("CM", "Commentary by"),
                            ("NT", "Notes by"),
                            ("TR", "Translation by"),
                        ],
                        max_length=2,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("kind", models.TextField(choices=[("PR", "Prose"), ("VR", "Verse")])),
                ("partial", models.BooleanField()),
                ("title", models.CharField(blank=True, max_length=255)),
                ("persons", models.ManyToManyField(to="translations.Person")),
            ],
        ),
        migrations.RemoveField(
            model_name="translation",
            name="authors",
        ),
        migrations.RemoveField(
            model_name="translation",
            name="language",
        ),
        migrations.RemoveField(
            model_name="translation",
            name="publications",
        ),
        migrations.RemoveField(
            model_name="translation",
            name="source_text",
        ),
        migrations.AlterModelOptions(
            name="series",
            options={"verbose_name_plural": "series"},
        ),
        migrations.RemoveField(
            model_name="volume",
            name="people",
        ),
        migrations.AddField(
            model_name="sourcetext",
            name="date",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="sourcetext",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sourcetext",
            name="kind",
            field=models.TextField(
                choices=[("PR", "Prose"), ("VR", "Verse")], default="VR"
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="PersonRole",
        ),
        migrations.DeleteModel(
            name="Translation",
        ),
        migrations.AddField(
            model_name="feature",
            name="source_text",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="translations.SourceText",
            ),
        ),
        migrations.AddField(
            model_name="feature",
            name="volumes",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="translations.Volume"
            ),
        ),
    ]
