# Generated by Django 3.0.8 on 2020-09-30 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0011_auto_20200929_2059"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feature",
            old_name="volumes",
            new_name="volume",
        ),
    ]
