# Generated by Django 3.0.8 on 2020-11-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0024_auto_20201107_2252"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="closeness_rating",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Low"), (2, "Average"), (3, "Excellent")],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="readability_rating",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Low"), (2, "Average"), (3, "Excellent")],
                null=True,
            ),
        ),
    ]
