# Generated by Django 3.0.8 on 2020-12-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0033_auto_20201128_0914"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="sort_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
