# Generated by Django 3.1.4 on 2021-01-30 23:04

from django.db import migrations


def approve_existing_objects(apps, schema_editor):
    for model in [
        apps.get_model("translations", "SourceText"),
        apps.get_model("translations", "Person"),
        apps.get_model("translations", "Publisher"),
        apps.get_model("translations", "Series"),
        apps.get_model("translations", "Volume"),
        apps.get_model("translations", "PublishedReview"),
    ]:
        for s in model.objects.all():
            s.approved = True
            s.save()


class Migration(migrations.Migration):
    dependencies = [
        ("translations", "0042_auto_20210130_1452"),
    ]
    operations = [
        migrations.RunPython(approve_existing_objects, migrations.RunPython.noop),
    ]
