# Generated by Django 3.1.4 on 2021-03-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0044_auto_20210219_2113"),
    ]

    operations = [
        migrations.AddField(
            model_name="volume",
            name="feature_bibliography",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="volume",
            name="feature_glossary",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="volume",
            name="feature_index",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="volume",
            name="feature_maps",
            field=models.BooleanField(default=False),
        ),
    ]
