# Generated by Django 3.1.4 on 2021-03-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0045_auto_20210306_1115"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcetext",
            name="sample_passage_license",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="sourcetext",
            name="sample_passage_license_link",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="sourcetext",
            name="sample_passage_source_link",
            field=models.URLField(null=True),
        ),
    ]
