# Generated by Django 3.1.4 on 2021-05-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0047_auto_20210308_2030"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcetext",
            name="coverage",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sourcetext",
            name="coverage_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
