# Generated by Django 4.0.2 on 2024-09-29 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_to_editions(apps, schema_editor):
    Volume = apps.get_model("translations", "Volume")
    Edition = apps.get_model("translations", "Edition")
    for v in Volume.objects.all():
        if v.isbn or v.oclc_number:
            e = Edition.objects.create(
                volume=v,
                isbn=v.isbn,
                oclc_number=v.oclc_number,
                edition_type="UK" # TODO
            )
            e.save()



class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('translations', '0050_auto_20210612_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('edition_type', models.CharField(choices=[('SC', 'Softcover'), ('HC', 'Hardcover'), ('EB', 'Ebook'), ('ON', 'Online Edition'), ('SN', 'Scan'), ('UK', 'Unknown')], max_length=2)),
                ('url', models.URLField(blank=True)),
                ('oclc_number', models.CharField(blank=True, max_length=32)),
                ('isbn', models.CharField(blank=True, max_length=32)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='translations.volume')),
            ],
            options={
                'ordering': ['volume'],
            },
        ),
        migrations.RunPython(migrate_to_editions, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='volume',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='oclc_number',
        ),
        migrations.AlterField(
            model_name='alternatename',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='language',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='link',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='publishedreview',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='series',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sourcetext',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usersubmission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
