# Generated by Django 4.0.2 on 2024-10-27 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0051_remove_volume_isbn_remove_volume_oclc_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='translations.book'),
        ),
    ]
