# Generated by Django 4.0.2 on 2024-10-31 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def migrate_to_volumereleases(apps, schema_editor):
    Volume = apps.get_model("translations", "Volume")
    VolumeRelease = apps.get_model("translations", "VolumeRelease")

    for v in Volume.objects.all():
        vr = VolumeRelease.objects.create(
                volume = v,
                release_type = "UK",
                isbn = v.isbn,
                oclc_number=v.oclc_number,
                published_date=v.published_date
            )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('translations', '0052_alter_volume_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolumeRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('release_type', models.CharField(choices=[('SC', 'Softcover'), ('HC', 'Hardcover'), ('EB', 'Ebook'), ('ON', 'Online Edition'), ('UK', 'Unknown')], default='UK', max_length=2)),
                ('oclc_number', models.CharField(blank=True, max_length=32)),
                ('published_date', models.DateField(blank=True)),
                ('isbn', models.CharField(blank=True, max_length=32)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='volumerelease',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='translations.volume'),
        ),
        migrations.RunPython(migrate_to_volumereleases, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='volume',
            name='book',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='edition_type',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='oclc_number',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='published_date',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
