# Generated by Django 4.0.2 on 2024-11-03 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('translations', '0053_volumerelease_remove_volume_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='set_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MultiVolumeSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='volume',
            name='volume_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='included_volumes', to='translations.multivolumeset'),
        ),
    ]
