# Generated by Django 4.0.2 on 2024-11-03 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0054_volume_set_index_multivolumeset_volume_volume_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volumerelease',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='translations.volume'),
        ),
    ]
