# Generated by Django 4.0.2 on 2024-11-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0055_alter_volumerelease_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='complete_with_other_volumes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feature',
            name='order_key',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
