# Generated by Django 3.0.8 on 2020-11-23 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterModelTable(
            name="user",
            table=None,
        ),
    ]
